# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/adrian/Documents/PROYECTOS/Simulador ATM/simulador-atm"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/adrian/Documents/PROYECTOS/Simulador ATM/simulador-atm"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/adrian/Documents/PROYECTOS/Simulador ATM/simulador-atm/CMakeFiles" "/Users/adrian/Documents/PROYECTOS/Simulador ATM/simulador-atm//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/adrian/Documents/PROYECTOS/Simulador ATM/simulador-atm/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simulador_atm

# Build rule for target.
simulador_atm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simulador_atm
.PHONY : simulador_atm

# fast build rule for target.
simulador_atm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/build
.PHONY : simulador_atm/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named info

# Build rule for target.
info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 info
.PHONY : info

# fast build rule for target.
info/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/info.dir/build.make CMakeFiles/info.dir/build
.PHONY : info/fast

src/Account.o: src/Account.cpp.o
.PHONY : src/Account.o

# target to build an object file
src/Account.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Account.cpp.o
.PHONY : src/Account.cpp.o

src/Account.i: src/Account.cpp.i
.PHONY : src/Account.i

# target to preprocess a source file
src/Account.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Account.cpp.i
.PHONY : src/Account.cpp.i

src/Account.s: src/Account.cpp.s
.PHONY : src/Account.s

# target to generate assembly for a file
src/Account.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Account.cpp.s
.PHONY : src/Account.cpp.s

src/Atm.o: src/Atm.cpp.o
.PHONY : src/Atm.o

# target to build an object file
src/Atm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Atm.cpp.o
.PHONY : src/Atm.cpp.o

src/Atm.i: src/Atm.cpp.i
.PHONY : src/Atm.i

# target to preprocess a source file
src/Atm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Atm.cpp.i
.PHONY : src/Atm.cpp.i

src/Atm.s: src/Atm.cpp.s
.PHONY : src/Atm.s

# target to generate assembly for a file
src/Atm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Atm.cpp.s
.PHONY : src/Atm.cpp.s

src/Transaction.o: src/Transaction.cpp.o
.PHONY : src/Transaction.o

# target to build an object file
src/Transaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Transaction.cpp.o
.PHONY : src/Transaction.cpp.o

src/Transaction.i: src/Transaction.cpp.i
.PHONY : src/Transaction.i

# target to preprocess a source file
src/Transaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Transaction.cpp.i
.PHONY : src/Transaction.cpp.i

src/Transaction.s: src/Transaction.cpp.s
.PHONY : src/Transaction.s

# target to generate assembly for a file
src/Transaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/Transaction.cpp.s
.PHONY : src/Transaction.cpp.s

src/User.o: src/User.cpp.o
.PHONY : src/User.o

# target to build an object file
src/User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/User.cpp.o
.PHONY : src/User.cpp.o

src/User.i: src/User.cpp.i
.PHONY : src/User.i

# target to preprocess a source file
src/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/User.cpp.i
.PHONY : src/User.cpp.i

src/User.s: src/User.cpp.s
.PHONY : src/User.s

# target to generate assembly for a file
src/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/User.cpp.s
.PHONY : src/User.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utiils.o: src/utiils.cpp.o
.PHONY : src/utiils.o

# target to build an object file
src/utiils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/utiils.cpp.o
.PHONY : src/utiils.cpp.o

src/utiils.i: src/utiils.cpp.i
.PHONY : src/utiils.i

# target to preprocess a source file
src/utiils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/utiils.cpp.i
.PHONY : src/utiils.cpp.i

src/utiils.s: src/utiils.cpp.s
.PHONY : src/utiils.s

# target to generate assembly for a file
src/utiils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulador_atm.dir/build.make CMakeFiles/simulador_atm.dir/src/utiils.cpp.s
.PHONY : src/utiils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... info"
	@echo "... run"
	@echo "... simulador_atm"
	@echo "... src/Account.o"
	@echo "... src/Account.i"
	@echo "... src/Account.s"
	@echo "... src/Atm.o"
	@echo "... src/Atm.i"
	@echo "... src/Atm.s"
	@echo "... src/Transaction.o"
	@echo "... src/Transaction.i"
	@echo "... src/Transaction.s"
	@echo "... src/User.o"
	@echo "... src/User.i"
	@echo "... src/User.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utiils.o"
	@echo "... src/utiils.i"
	@echo "... src/utiils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

